package com.morallenplay.vanillacookbook.registry;

import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;

public class FoodRegistry {
	
	public static final FoodProperties COOKED_BAMBOO = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties COOKED_BEETROOT = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.4F).build());
	public static final FoodProperties COOKED_EGG = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.45F).build());
	public static final FoodProperties GRILLED_MELON = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.45F).build());
	public static final FoodProperties BAKED_APPLE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.4F).build());
	public static final FoodProperties COOKED_TURTLE_EGG = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.8F).build());
	public static final FoodProperties COOKED_SNIFFER_EGG = (new FoodProperties.Builder().nutrition(9).saturationModifier(0.5F).build());
	public static final FoodProperties CACTUS_SLICE = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.6F).build());
	public static final FoodProperties COOKED_CACTUS_SLICE = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.75F).build());
	public static final FoodProperties CHEESE = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties GARDEN_SOUP = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.6F).build());
	public static final FoodProperties PUMPKIN_SOUP = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.75F).build());
	public static final FoodProperties FISH_STEW = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.2F).build());
	public static final FoodProperties VEGETABLE_STEW = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.85F).build());
	public static final FoodProperties MEATY_STEW = (new FoodProperties.Builder().nutrition(7).saturationModifier(1.0F).build());
	public static final FoodProperties CHICKEN_SOUP = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.8F).build());
	public static final FoodProperties INK_SOUP = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.1F).build());
	public static final FoodProperties GLOW_INK_SOUP = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.15F).effect(() -> new MobEffectInstance(MobEffects.GLOWING, 100, 0), 0.1F).build());
	public static final FoodProperties FUNGUS_STEW = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.6F).build());
	public static final FoodProperties SMOLDERING_STEW = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.6F).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 200, 0), 1F).build());
	public static final FoodProperties PLAIN_SALAD = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.3F).build());
	public static final FoodProperties KELP_SALAD = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.6F).build());
	public static final FoodProperties FRUIT_SALAD = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.6F).build());
	public static final FoodProperties GOLDEN_FRUIT_SALAD = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.75F).effect(() -> new MobEffectInstance(MobEffects.HEAL, 1, 0), 1F).build());
	public static final FoodProperties ROOT_SALAD = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.1F).build());
	public static final FoodProperties MASHED_POTATOES = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.65F).build());
	public static final FoodProperties APPLE_SAUCE = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.6F).build());
	public static final FoodProperties MUSHROOM_SCRAMBLED_EGGS = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.65F).build());
	public static final FoodProperties PUDDING = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.6F).build());
	public static final FoodProperties CHOCOLATE_PUDDING = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.75F).build());
	public static final FoodProperties JELLY = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.45F).effect(() -> new MobEffectInstance(MobEffects.OOZING, 200, 0), 0.5F).build());
	public static final FoodProperties MAGMA_JELLY = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.45F).effect(() -> new MobEffectInstance(MobEffects.OOZING, 200, 0), 0.5F).build());
	public static final FoodProperties APPLE_PIE = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.3F).build());
	public static final FoodProperties BEETROOT_PIE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.35F).build());
	public static final FoodProperties BERRY_PIE = (new FoodProperties.Builder().nutrition(7).saturationModifier(0.3F).build());
	public static final FoodProperties WART_PIE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.25F).build());
	public static final FoodProperties ENDER_PIE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.35F).build());
	public static final FoodProperties POISONOUS_PIE = (new FoodProperties.Builder().nutrition(10).saturationModifier(0.72F).effect(() -> new MobEffectInstance(MobEffects.POISON, 300, 2), 1F).effect(() -> new MobEffectInstance(MobEffects.CONFUSION, 300, 0), 1F).build());
	public static final FoodProperties BERRY_COOKIE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties HONEY_COOKIE = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.1F).build());
	public static final FoodProperties POTATO_COOKIE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties PUMPKIN_COOKIE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties SUNFLOWER_SEED_COOKIE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties PANCAKE = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.66F).build());
	public static final FoodProperties BERRY_PANCAKE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.65F).build());
	public static final FoodProperties HONEY_PANCAKE = (new FoodProperties.Builder().nutrition(9).saturationModifier(0.7F).build());
	public static final FoodProperties BACON_PANCAKE = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.8F).build());
	public static final FoodProperties CREEPE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.6F).build());
	public static final FoodProperties BROWNIE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.55F).build());
	public static final FoodProperties BERRY_BROWNIE = (new FoodProperties.Builder().nutrition(7).saturationModifier(0.5F).build());
	public static final FoodProperties CHORUS_ROLL = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.75F).alwaysEdible().build());
	public static final FoodProperties ICE_CREAM = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.6F).build());
	public static final FoodProperties CHOCOLATE_ICE_CREAM = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.6F).build());
	public static final FoodProperties BERRY_ICE_CREAM = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.8F).build());
	public static final FoodProperties NEAPOLITAN_ICE_CREAM = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.8F).build());
	public static final FoodProperties PUMPSICLE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.45F).build());
	public static final FoodProperties SNOW_HORN = (new FoodProperties.Builder().nutrition(7).saturationModifier(0.6F).build());
	public static final FoodProperties SWEET_SKEWER = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.15F).build());
	public static final FoodProperties GLAZED_GLOW_BERRIES = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.4F).effect(() -> new MobEffectInstance(MobEffects.NIGHT_VISION, 400, 0), 1F).effect(() -> new MobEffectInstance(MobEffects.GLOWING, 400, 0), 1F).build());
	public static final FoodProperties POTATO_CHIPS = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.3F).fast().alwaysEdible().build());
	public static final FoodProperties HOT_POTATO_CHIPS = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).fast().alwaysEdible().build());
	public static final FoodProperties BEET_CHIPS = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.45F).fast().alwaysEdible().build());
	public static final FoodProperties APPLE_CHIPS = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.3F).fast().alwaysEdible().build());
	public static final FoodProperties HONEY_CANDY = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.175F).fast().alwaysEdible().build());
	public static final FoodProperties BERRY_CANDY = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.1F).fast().alwaysEdible().build());
	public static final FoodProperties WARPED_GUMMY = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).fast().alwaysEdible().build());
	public static final FoodProperties CHOCOLATE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.2F).fast().alwaysEdible().build());
	public static final FoodProperties PITCHER_PRALINE = (new FoodProperties.Builder().nutrition(1).saturationModifier(0.6F).fast().alwaysEdible().build());
	public static final FoodProperties COTTON_CANDY = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.4F).alwaysEdible().fast().effect(() -> new MobEffectInstance(MobEffects.LEVITATION, 5, 24, false, false, false), 1F).build());
	public static final FoodProperties SWORD_LOLLIPOP = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.15F).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 600, 0), 1.0F).build());
	public static final FoodProperties TRAIL_MIX = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.2F).build());
	public static final FoodProperties HOT_CHICKEN_DRUMSTICK = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.5F).build());
	public static final FoodProperties FISH_AND_CHIPS = (new FoodProperties.Builder().nutrition(7).saturationModifier(0.7F).build());
	public static final FoodProperties KEBAB = (new FoodProperties.Builder().nutrition(9).saturationModifier(0.7F).build());
	public static final FoodProperties MEATLOAF = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.95F).build());
	public static final FoodProperties MEATBALL = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.6F).fast().build());
	public static final FoodProperties SPICY_MEATBALL = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.6F).fast().build());
	public static final FoodProperties RAW_BEET_MEAT = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties COOKED_BEET_MEAT = (new FoodProperties.Builder().nutrition(6).saturationModifier(1.05F).build());
	public static final FoodProperties FRENCH_TOAST = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.6F).build());
	public static final FoodProperties POTATO_PANCAKE = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.5F).build());
	public static final FoodProperties STUFFED_SEA_PICKLE = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.6F).build());
	public static final FoodProperties MINERS_SALAD = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.15F).build());
	public static final FoodProperties NETHERITE_APPLE = (new FoodProperties.Builder().nutrition(4).saturationModifier(1.2F).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 6000, 1), 1.0F).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 6000, 0), 1.0F).effect(() -> new MobEffectInstance(MobEffects.DIG_SPEED, 6000, 1), 1.0F).effect(() -> new MobEffectInstance(MobEffects.ABSORPTION, 2400, 1), 1.0F).alwaysEdible().build());
	public static final FoodProperties SCULKY_CHEESE = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).alwaysEdible().build());
	public static final FoodProperties CHOCOLATE_EGG = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.4F).build());
	public static final FoodProperties APPLE_JUICE = (new FoodProperties.Builder().nutrition(1).saturationModifier(3.6F).alwaysEdible().build());
	public static final FoodProperties BERRY_JUICE = (new FoodProperties.Builder().nutrition(1).saturationModifier(2.0F).alwaysEdible().build());
	public static final FoodProperties CACTUS_JUICE = (new FoodProperties.Builder().nutrition(1).saturationModifier(2.4F).alwaysEdible().build());
	public static final FoodProperties MELON_JUICE = (new FoodProperties.Builder().nutrition(1).saturationModifier(2.4F).alwaysEdible().build());
	public static final FoodProperties SEA_PICKLE_JUICE = (new FoodProperties.Builder().nutrition(1).saturationModifier(1.8F).alwaysEdible().build());
	public static final FoodProperties CHORUS_JUICE = (new FoodProperties.Builder().nutrition(1).saturationModifier(3.6F).alwaysEdible().build());
	public static final FoodProperties LEAF_TEA = (new FoodProperties.Builder().nutrition(1).saturationModifier(4.8F).alwaysEdible().build());
	public static final FoodProperties CHERRY_BLOSSOM_TEA = (new FoodProperties.Builder().nutrition(1).saturationModifier(5.4F).alwaysEdible().build());
	public static final FoodProperties FLOWER_TEA = (new FoodProperties.Builder().nutrition(1).saturationModifier(8.0F).alwaysEdible().build());
	public static final FoodProperties MILK_BOTTLE = (new FoodProperties.Builder().nutrition(1).saturationModifier(1.2F).alwaysEdible().build());
	public static final FoodProperties CHOCOLATE_MILK = (new FoodProperties.Builder().nutrition(1).saturationModifier(2.4F).alwaysEdible().build());
	public static final FoodProperties BERRY_MILK = (new FoodProperties.Builder().nutrition(1).saturationModifier(2.4F).alwaysEdible().build());
	public static final FoodProperties APPLE_SODA = (new FoodProperties.Builder().nutrition(1).saturationModifier(7.2F).effect(() -> new MobEffectInstance(MobEffects.ABSORPTION, 400, 2), 1F).alwaysEdible().build());
	public static final FoodProperties BERRY_SODA = (new FoodProperties.Builder().nutrition(1).saturationModifier(4.8F).effect(() -> new MobEffectInstance(MobEffects.DIG_SPEED, 400, 1), 1F).alwaysEdible().build());
	public static final FoodProperties CACTUS_SODA = (new FoodProperties.Builder().nutrition(1).saturationModifier(6.0F).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 400, 1), 1F).alwaysEdible().build());
	public static final FoodProperties MELON_SODA = (new FoodProperties.Builder().nutrition(1).saturationModifier(5.4F).effect(() -> new MobEffectInstance(MobEffects.HEAL, 1, 1), 1F).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 400, 0), 1F).alwaysEdible().build());
	public static final FoodProperties SEA_PICKLE_SODA = (new FoodProperties.Builder().nutrition(1).saturationModifier(4.0F).effect(() -> new MobEffectInstance(MobEffects.DOLPHINS_GRACE, 400, 0), 1F).alwaysEdible().build());
	public static final FoodProperties CHORUS_SODA = (new FoodProperties.Builder().nutrition(1).saturationModifier(7.2F).effect(() -> new MobEffectInstance(MobEffects.LEVITATION, 200, 4), 1F).effect(() -> new MobEffectInstance(MobEffects.SLOW_FALLING, 240, 0), 1F).alwaysEdible().build());
	
	public static final FoodProperties THE_SLUDGE = (new FoodProperties.Builder().nutrition(0).saturationModifier(0F).alwaysEdible().build());
	
	public static final FoodProperties PIZZA = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.8F).build());
	public static final FoodProperties BERRY_CAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties CARROT_CAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties CHEESECAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties CHOCOLATE_CAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties MOHNKUCHEN_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties ICE_CREAM_CAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties ROSE_CAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties CHORUS_CAKE_SLICE = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.1F).build());
	public static final FoodProperties BOOK_CAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties GLOW_BERRY_CAKE_SLICE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	
	public static final FoodProperties ROSE_ROCK_CANDY = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.3F).build());
	public static final FoodProperties POLISHED_ROSE_ROCK_CANDY = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.32F).effect(() -> new MobEffectInstance(MobEffects.DIG_SPEED, 600, 0), 1F).alwaysEdible().build());
	
	public static final FoodProperties MANA_ROLL = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.54F).build());
	public static final FoodProperties TATER_PUFFS = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.3F).fast().effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 2, 5), 0.5F).alwaysEdible().build());
	
}
