package com.morallenplay.vanillacookbook.registry;

import com.morallenplay.vanillacookbook.VanillaCookbook;
import com.morallenplay.vanillacookbook.item.CactusSliceItem;
import com.morallenplay.vanillacookbook.item.CheeseItem;
import com.morallenplay.vanillacookbook.item.ChorusJuiceItem;
import com.morallenplay.vanillacookbook.item.CureItem;
import com.morallenplay.vanillacookbook.item.IceCreamItem;
import com.morallenplay.vanillacookbook.item.JuiceItem;
import com.morallenplay.vanillacookbook.item.MilkBottleItem;
import com.morallenplay.vanillacookbook.item.SculkFoodItem;
import com.morallenplay.vanillacookbook.item.SludgeItem;
import com.morallenplay.vanillacookbook.item.TooltipItem;
import com.morallenplay.vanillacookbook.item.ContainerItem;
import com.morallenplay.vanillacookbook.item.ChorusDirectionItem;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.ChorusFruitItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Rarity;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.minecraft.world.effect.MobEffects;

public class ItemRegistry {
	public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(VanillaCookbook.MODID);
	
	
	public static final DeferredItem<Item> COOKED_BAMBOO = ITEMS.register("cooked_bamboo", () -> new Item(new Item.Properties().food(FoodRegistry.COOKED_BAMBOO)));
	public static final DeferredItem<Item> COOKED_BEETROOT = ITEMS.register("cooked_beetroot", () -> new Item(new Item.Properties().food(FoodRegistry.COOKED_BEETROOT)));
	public static final DeferredItem<Item> COOKED_EGG = ITEMS.register("cooked_egg", () -> new Item(new Item.Properties().food(FoodRegistry.COOKED_EGG)));
	public static final DeferredItem<Item> GRILLED_MELON = ITEMS.register("grilled_melon", () -> new Item(new Item.Properties().food(FoodRegistry.GRILLED_MELON)));
	public static final DeferredItem<Item> BAKED_APPLE = ITEMS.register("baked_apple", () -> new Item(new Item.Properties().food(FoodRegistry.BAKED_APPLE)));
	public static final DeferredItem<Item> COOKED_TURTLE_EGG = ITEMS.register("cooked_turtle_egg", () -> new Item(new Item.Properties().food(FoodRegistry.COOKED_TURTLE_EGG)));
	public static final DeferredItem<Item> COOKED_SNIFFER_EGG = ITEMS.register("cooked_sniffer_egg", () -> new Item(new Item.Properties().food(FoodRegistry.COOKED_SNIFFER_EGG)));
	public static final DeferredItem<Item> CACTUS_SLICE = ITEMS.register("cactus_slice", () -> new CactusSliceItem(new Item.Properties().food(FoodRegistry.CACTUS_SLICE), 2.0F, 0.5F));
	public static final DeferredItem<Item> COOKED_CACTUS_SLICE = ITEMS.register("cooked_cactus_slice", () -> new CactusSliceItem(new Item.Properties().food(FoodRegistry.COOKED_CACTUS_SLICE), 1.0F, 0.25F));
	public static final DeferredItem<Item> CHEESE = ITEMS.register("cheese", () -> new CheeseItem(new Item.Properties().food(FoodRegistry.CHEESE), false, true));
	public static final DeferredItem<Item> GARDEN_SOUP = ITEMS.register("garden_soup", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.GARDEN_SOUP).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> PUMPKIN_SOUP = ITEMS.register("pumpkin_soup", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.PUMPKIN_SOUP).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> FISH_STEW = ITEMS.register("fish_stew", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.FISH_STEW).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> VEGETABLE_STEW = ITEMS.register("vegetable_stew", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.VEGETABLE_STEW).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> MEATY_STEW = ITEMS.register("meaty_stew", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.MEATY_STEW).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> CHICKEN_SOUP = ITEMS.register("chicken_soup", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.CHICKEN_SOUP).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> INK_SOUP = ITEMS.register("ink_soup", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.INK_SOUP).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> GLOW_INK_SOUP = ITEMS.register("glow_ink_soup", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.GLOW_INK_SOUP).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> FUNGUS_STEW = ITEMS.register("fungus_stew", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.FUNGUS_STEW).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> SMOLDERING_STEW = ITEMS.register("smoldering_stew", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.SMOLDERING_STEW).craftRemainder(Items.BOWL).stacksTo(16), true));
	public static final DeferredItem<Item> PLAIN_SALAD = ITEMS.register("plain_salad", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.PLAIN_SALAD).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> KELP_SALAD = ITEMS.register("kelp_salad", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.KELP_SALAD).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> FRUIT_SALAD = ITEMS.register("fruit_salad", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.FRUIT_SALAD).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> GOLDEN_FRUIT_SALAD = ITEMS.register("golden_fruit_salad", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.GOLDEN_FRUIT_SALAD).craftRemainder(Items.BOWL).stacksTo(16), false, true));
	public static final DeferredItem<Item> ROOT_SALAD = ITEMS.register("root_salad", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.ROOT_SALAD).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> MASHED_POTATOES = ITEMS.register("mashed_potatoes", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.MASHED_POTATOES).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> APPLE_SAUCE = ITEMS.register("apple_sauce", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.MASHED_POTATOES).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> MUSHROOM_SCRAMBLED_EGGS = ITEMS.register("mushroom_scrambled_eggs", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.MUSHROOM_SCRAMBLED_EGGS).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> PUDDING = ITEMS.register("pudding", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.PUDDING).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> CHOCOLATE_PUDDING = ITEMS.register("chocolate_pudding", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.CHOCOLATE_PUDDING).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> JELLY = ITEMS.register("jelly", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.JELLY).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> MAGMA_JELLY = ITEMS.register("magma_jelly", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.MAGMA_JELLY).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final DeferredItem<Item> APPLE_PIE = ITEMS.register("apple_pie", () -> new Item(new Item.Properties().food(FoodRegistry.APPLE_PIE)));
	public static final DeferredItem<Item> BEETROOT_PIE = ITEMS.register("beetroot_pie", () -> new Item(new Item.Properties().food(FoodRegistry.BEETROOT_PIE)));
	public static final DeferredItem<Item> BERRY_PIE = ITEMS.register("berry_pie", () -> new Item(new Item.Properties().food(FoodRegistry.BERRY_PIE)));
	public static final DeferredItem<Item> WART_PIE = ITEMS.register("wart_pie", () -> new Item(new Item.Properties().food(FoodRegistry.WART_PIE)));
	public static final DeferredItem<Item> ENDER_PIE = ITEMS.register("ender_pie", () -> new ChorusDirectionItem(new Item.Properties().food(FoodRegistry.ENDER_PIE)));
	public static final DeferredItem<Item> POISONOUS_PIE = ITEMS.register("poisonous_pie", () -> new TooltipItem(new Item.Properties().food(FoodRegistry.POISONOUS_PIE), true));
	public static final DeferredItem<Item> BERRY_COOKIE = ITEMS.register("berry_cookie", () -> new Item(new Item.Properties().food(FoodRegistry.BERRY_COOKIE)));
	public static final DeferredItem<Item> HONEY_COOKIE = ITEMS.register("honey_cookie", () -> new Item(new Item.Properties().food(FoodRegistry.HONEY_COOKIE)));
	public static final DeferredItem<Item> POTATO_COOKIE = ITEMS.register("potato_cookie", () -> new Item(new Item.Properties().food(FoodRegistry.POTATO_COOKIE)));
	public static final DeferredItem<Item> PUMPKIN_COOKIE = ITEMS.register("pumpkin_cookie", () -> new Item(new Item.Properties().food(FoodRegistry.PUMPKIN_COOKIE)));
	public static final DeferredItem<Item> SUNFLOWER_SEED_COOKIE = ITEMS.register("sunflower_seed_cookie", () -> new Item(new Item.Properties().food(FoodRegistry.SUNFLOWER_SEED_COOKIE)));
	public static final DeferredItem<Item> PANCAKE = ITEMS.register("pancake", () -> new Item(new Item.Properties().food(FoodRegistry.PANCAKE)));
	public static final DeferredItem<Item> BERRY_PANCAKE = ITEMS.register("berry_pancake", () -> new Item(new Item.Properties().food(FoodRegistry.BERRY_PANCAKE)));
	public static final DeferredItem<Item> HONEY_PANCAKE = ITEMS.register("honey_pancake", () -> new Item(new Item.Properties().food(FoodRegistry.HONEY_PANCAKE)));
	public static final DeferredItem<Item> BACON_PANCAKE = ITEMS.register("bacon_pancake", () -> new Item(new Item.Properties().food(FoodRegistry.BACON_PANCAKE)));
	public static final DeferredItem<Item> CREEPE = ITEMS.register("creepe", () -> new Item(new Item.Properties().food(FoodRegistry.CREEPE)));
	public static final DeferredItem<Item> BROWNIE = ITEMS.register("brownie", () -> new Item(new Item.Properties().food(FoodRegistry.BROWNIE)));
	public static final DeferredItem<Item> BERRY_BROWNIE = ITEMS.register("berry_brownie", () -> new Item(new Item.Properties().food(FoodRegistry.BERRY_BROWNIE)));
	public static final DeferredItem<Item> CHORUS_ROLL = ITEMS.register("chorus_roll", () -> new ChorusDirectionItem(new Item.Properties().food(FoodRegistry.CHORUS_ROLL)));
	public static final DeferredItem<Item> ICE_CREAM = ITEMS.register("ice_cream", () -> new IceCreamItem(new Item.Properties().food(FoodRegistry.ICE_CREAM), false, true));
	public static final DeferredItem<Item> CHOCOLATE_ICE_CREAM = ITEMS.register("chocolate_ice_cream", () -> new IceCreamItem(new Item.Properties().food(FoodRegistry.CHOCOLATE_ICE_CREAM), false, true));
	public static final DeferredItem<Item> BERRY_ICE_CREAM = ITEMS.register("berry_ice_cream", () -> new IceCreamItem(new Item.Properties().food(FoodRegistry.BERRY_ICE_CREAM), false, true));
	public static final DeferredItem<Item> NEAPOLITAN_ICE_CREAM = ITEMS.register("neapolitan_ice_cream", () -> new IceCreamItem(new Item.Properties().food(FoodRegistry.NEAPOLITAN_ICE_CREAM), false, true));
	public static final DeferredItem<Item> PUMPSICLE = ITEMS.register("pumpsicle", () -> new IceCreamItem(new Item.Properties().food(FoodRegistry.PUMPSICLE).craftRemainder(Items.STICK).stacksTo(16), false, true));
	public static final DeferredItem<Item> SNOW_HORN = ITEMS.register("snow_horn", () -> new IceCreamItem(new Item.Properties().food(FoodRegistry.SNOW_HORN), false, true));
	public static final DeferredItem<Item> SWEET_SKEWER = ITEMS.register("sweet_skewer", () -> new Item(new Item.Properties().food(FoodRegistry.SWEET_SKEWER)));
	public static final DeferredItem<Item> GLAZED_GLOW_BERRIES = ITEMS.register("glazed_glow_berries", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.GLAZED_GLOW_BERRIES).craftRemainder(Items.STICK).stacksTo(16), true));
	public static final DeferredItem<Item> POTATO_CHIPS = ITEMS.register("potato_chips", () -> new CureItem(new Item.Properties().food(FoodRegistry.POTATO_CHIPS), MobEffects.HUNGER, 0.5F, false, true));
	public static final DeferredItem<Item> HOT_POTATO_CHIPS = ITEMS.register("hot_potato_chips", () -> new CureItem(new Item.Properties().food(FoodRegistry.HOT_POTATO_CHIPS), MobEffects.HUNGER, 0.5F, false, true));
	public static final DeferredItem<Item> BEET_CHIPS = ITEMS.register("beet_chips", () -> new CureItem(new Item.Properties().food(FoodRegistry.BEET_CHIPS), MobEffects.HUNGER, 0.5F, false, true));
	public static final DeferredItem<Item> APPLE_CHIPS = ITEMS.register("apple_chips", () -> new CureItem(new Item.Properties().food(FoodRegistry.APPLE_CHIPS), MobEffects.HUNGER, 0.5F, false, true));
	public static final DeferredItem<Item> HONEY_CANDY = ITEMS.register("honey_candy", () -> new CureItem(new Item.Properties().food(FoodRegistry.HONEY_CANDY), MobEffects.HUNGER, 0.3F, false, true));
	public static final DeferredItem<Item> BERRY_CANDY = ITEMS.register("berry_candy", () -> new CureItem(new Item.Properties().food(FoodRegistry.BERRY_CANDY), MobEffects.HUNGER, 0.3F, false, true));
	public static final DeferredItem<Item> WARPED_GUMMY = ITEMS.register("warped_gummy", () -> new CureItem(new Item.Properties().food(FoodRegistry.WARPED_GUMMY), MobEffects.WITHER, 1.0F, false, true));
	public static final DeferredItem<Item> CHOCOLATE = ITEMS.register("chocolate", () -> new CureItem(new Item.Properties().food(FoodRegistry.CHOCOLATE), MobEffects.HUNGER, 0.3F, false, true));
	public static final DeferredItem<Item> PITCHER_PRALINE = ITEMS.register("pitcher_praline", () -> new CureItem(new Item.Properties().food(FoodRegistry.PITCHER_PRALINE), MobEffects.DIG_SLOWDOWN, 1.0F, false, true));
	public static final DeferredItem<Item> COTTON_CANDY = ITEMS.register("cotton_candy", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.COTTON_CANDY).craftRemainder(Items.BREEZE_ROD).stacksTo(16), false, true));
	public static final DeferredItem<Item> SWORD_LOLLIPOP = ITEMS.register("sword_lollipop", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.SWORD_LOLLIPOP).craftRemainder(Items.STICK).stacksTo(16), true));
	public static final DeferredItem<Item> TRAIL_MIX = ITEMS.register("trail_mix", () -> new Item(new Item.Properties().food(FoodRegistry.TRAIL_MIX)));
	public static final DeferredItem<Item> HOT_CHICKEN_DRUMSTICK = ITEMS.register("hot_chicken_drumstick", () -> new Item(new Item.Properties().food(FoodRegistry.HOT_CHICKEN_DRUMSTICK)));
	public static final DeferredItem<Item> FISH_AND_CHIPS = ITEMS.register("fish_and_chips", () -> new Item(new Item.Properties().food(FoodRegistry.FISH_AND_CHIPS)));
	public static final DeferredItem<Item> KEBAB = ITEMS.register("kebab", () -> new ContainerItem(new Item.Properties().food(FoodRegistry.KEBAB).craftRemainder(Items.STICK).stacksTo(16)));
	public static final DeferredItem<Item> MEATLOAF = ITEMS.register("meatloaf", () -> new Item(new Item.Properties().food(FoodRegistry.MEATLOAF)));
	public static final DeferredItem<Item> MEATBALL = ITEMS.register("meatball", () -> new Item(new Item.Properties().food(FoodRegistry.MEATBALL)));
	public static final DeferredItem<Item> SPICY_MEATBALL = ITEMS.register("spicy_meatball", () -> new Item(new Item.Properties().food(FoodRegistry.SPICY_MEATBALL)));
	public static final DeferredItem<Item> RAW_BEET_MEAT = ITEMS.register("raw_beet_meat", () -> new Item(new Item.Properties().food(FoodRegistry.RAW_BEET_MEAT)));
	public static final DeferredItem<Item> COOKED_BEET_MEAT = ITEMS.register("cooked_beet_meat", () -> new Item(new Item.Properties().food(FoodRegistry.COOKED_BEET_MEAT)));
	public static final DeferredItem<Item> FRENCH_TOAST = ITEMS.register("french_toast", () -> new Item(new Item.Properties().food(FoodRegistry.FRENCH_TOAST)));
	public static final DeferredItem<Item> POTATO_PANCAKE = ITEMS.register("potato_pancake", () -> new Item(new Item.Properties().food(FoodRegistry.POTATO_PANCAKE)));
	public static final DeferredItem<Item> STUFFED_SEA_PICKLE = ITEMS.register("stuffed_sea_pickle", () -> new CheeseItem(new Item.Properties().food(FoodRegistry.STUFFED_SEA_PICKLE), false, true));
	public static final DeferredItem<Item> MINERS_SALAD = ITEMS.register("miners_salad", () -> new Item(new Item.Properties().food(FoodRegistry.MINERS_SALAD)));
	public static final DeferredItem<Item> NETHERITE_APPLE = ITEMS.register("netherite_apple", () -> new TooltipItem(new Item.Properties().food(FoodRegistry.NETHERITE_APPLE).fireResistant().rarity(Rarity.RARE), true));
	public static final DeferredItem<Item> SCULKY_CHEESE = ITEMS.register("sculky_cheese", () -> new SculkFoodItem(new Item.Properties().food(FoodRegistry.SCULKY_CHEESE), false, true));
	public static final DeferredItem<Item> CHOCOLATE_EGG = ITEMS.register("chocolate_egg", () -> new Item(new Item.Properties().food(FoodRegistry.CHOCOLATE_EGG)));
	public static final DeferredItem<Item> APPLE_JUICE = ITEMS.register("apple_juice", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.APPLE_JUICE).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> BERRY_JUICE = ITEMS.register("berry_juice", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.BERRY_JUICE).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> CACTUS_JUICE = ITEMS.register("cactus_juice", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.CACTUS_JUICE).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> MELON_JUICE = ITEMS.register("melon_juice", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.MELON_JUICE).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> SEA_PICKLE_JUICE = ITEMS.register("sea_pickle_juice", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.SEA_PICKLE_JUICE).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> CHORUS_JUICE = ITEMS.register("chorus_juice", () -> new ChorusJuiceItem(new Item.Properties().food(FoodRegistry.CHORUS_JUICE).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> LEAF_TEA = ITEMS.register("leaf_tea", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.LEAF_TEA).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> CHERRY_BLOSSOM_TEA = ITEMS.register("cherry_blossom_tea", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.CHERRY_BLOSSOM_TEA).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> FLOWER_TEA = ITEMS.register("flower_tea", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.FLOWER_TEA).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final DeferredItem<Item> MILK_BOTTLE = ITEMS.register("milk_bottle", () -> new MilkBottleItem(new Item.Properties().food(FoodRegistry.MILK_BOTTLE).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16), false, true));
	public static final DeferredItem<Item> CHOCOLATE_MILK = ITEMS.register("chocolate_milk", () -> new MilkBottleItem(new Item.Properties().food(FoodRegistry.CHOCOLATE_MILK).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16), false, true));
	public static final DeferredItem<Item> BERRY_MILK = ITEMS.register("berry_milk", () -> new MilkBottleItem(new Item.Properties().food(FoodRegistry.BERRY_MILK).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16), false, true));
	public static final DeferredItem<Item> APPLE_SODA = ITEMS.register("apple_soda", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.APPLE_SODA).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16), true));
	public static final DeferredItem<Item> BERRY_SODA = ITEMS.register("berry_soda", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.BERRY_SODA).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16), true));
	public static final DeferredItem<Item> CACTUS_SODA = ITEMS.register("cactus_soda", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.CACTUS_SODA).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16), true));
	public static final DeferredItem<Item> MELON_SODA = ITEMS.register("melon_soda", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.MELON_SODA).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16), true));
	public static final DeferredItem<Item> SEA_PICKLE_SODA = ITEMS.register("sea_pickle_soda", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.SEA_PICKLE_SODA).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16), true));
	public static final DeferredItem<Item> CHORUS_SODA = ITEMS.register("chorus_soda", () -> new JuiceItem(new Item.Properties().food(FoodRegistry.CHORUS_SODA).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16), true));
	
	public static final DeferredItem<Item> THE_SLUDGE = ITEMS.register("the_sludge", () -> new SludgeItem(new Item.Properties().food(FoodRegistry.THE_SLUDGE), false, true));
	
	public static final DeferredItem<Item> PIZZA = ITEMS.register("pizza", () -> new Item(new Item.Properties().food(FoodRegistry.PIZZA)));
	public static final DeferredItem<Item> BERRY_CAKE_SLICE = ITEMS.register("berry_cake_slice", () -> new Item(new Item.Properties().food(FoodRegistry.BERRY_CAKE_SLICE)));
	public static final DeferredItem<Item> CARROT_CAKE_SLICE = ITEMS.register("carrot_cake_slice", () -> new Item(new Item.Properties().food(FoodRegistry.CARROT_CAKE_SLICE)));
	public static final DeferredItem<Item> CHEESECAKE_SLICE = ITEMS.register("cheesecake_slice", () -> new CheeseItem(new Item.Properties().food(FoodRegistry.CHEESECAKE_SLICE), false, true));
	public static final DeferredItem<Item> CHOCOLATE_CAKE_SLICE = ITEMS.register("chocolate_cake_slice", () -> new Item(new Item.Properties().food(FoodRegistry.CHOCOLATE_CAKE_SLICE)));
	public static final DeferredItem<Item> MOHNKUCHEN_SLICE = ITEMS.register("mohnkuchen_slice", () -> new Item(new Item.Properties().food(FoodRegistry.MOHNKUCHEN_SLICE)));
	public static final DeferredItem<Item> ICE_CREAM_CAKE_SLICE = ITEMS.register("ice_cream_cake_slice", () -> new Item(new Item.Properties().food(FoodRegistry.ICE_CREAM_CAKE_SLICE)));
	public static final DeferredItem<Item> ROSE_CAKE_SLICE = ITEMS.register("rose_cake_slice", () -> new Item(new Item.Properties().food(FoodRegistry.ROSE_CAKE_SLICE)));
	public static final DeferredItem<Item> CHORUS_CAKE_SLICE = ITEMS.register("chorus_cake_slice", () -> new ChorusFruitItem(new Item.Properties().food(FoodRegistry.CHORUS_CAKE_SLICE)));
	public static final DeferredItem<Item> BOOK_CAKE_SLICE = ITEMS.register("book_cake_slice", () -> new Item(new Item.Properties().food(FoodRegistry.BOOK_CAKE_SLICE)));
	public static final DeferredItem<Item> GLOW_BERRY_CAKE_SLICE = ITEMS.register("glow_berry_cake_slice", () -> new Item(new Item.Properties().food(FoodRegistry.GLOW_BERRY_CAKE_SLICE)));
	
	public static final DeferredItem<Item> ROSE_ROCK_CANDY = ITEMS.register("rose_rock_candy", () -> new CureItem(new Item.Properties().food(FoodRegistry.ROSE_ROCK_CANDY), MobEffects.POISON, 1.0F, false, true));
	public static final DeferredItem<Item> POLISHED_ROSE_ROCK_CANDY = ITEMS.register("polished_rose_rock_candy", () -> new CureItem(new Item.Properties().food(FoodRegistry.POLISHED_ROSE_ROCK_CANDY), MobEffects.POISON, 1.0F, true, true));
	
	public static final DeferredItem<Item> MANA_ROLL = ITEMS.register("mana_roll", () -> new CheeseItem(new Item.Properties().food(FoodRegistry.MANA_ROLL), false, true));
	public static final DeferredItem<Item> TATER_PUFFS = ITEMS.register("tater_puffs", () -> new CureItem(new Item.Properties().food(FoodRegistry.TATER_PUFFS), MobEffects.HUNGER, 0.75F, false, true));
	
	public static final DeferredItem<Item> BERRY_CAKE = ITEMS.register("berry_cake", () -> (new BlockItem(BlockRegistry.BERRY_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> CARROT_CAKE = ITEMS.register("carrot_cake", () -> (new BlockItem(BlockRegistry.CARROT_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> CHEESECAKE = ITEMS.register("cheesecake", () -> (new BlockItem(BlockRegistry.CHEESECAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> CHOCOLATE_CAKE = ITEMS.register("chocolate_cake", () -> (new BlockItem(BlockRegistry.CHOCOLATE_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> MOHNKUCHEN = ITEMS.register("mohnkuchen", () -> (new BlockItem(BlockRegistry.MOHNKUCHEN.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> ICE_CREAM_CAKE = ITEMS.register("ice_cream_cake", () -> (new BlockItem(BlockRegistry.ICE_CREAM_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> ROSE_CAKE = ITEMS.register("rose_cake", () -> (new BlockItem(BlockRegistry.ROSE_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> CHORUS_CAKE = ITEMS.register("chorus_cake", () -> (new BlockItem(BlockRegistry.CHORUS_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> BOOK_CAKE = ITEMS.register("book_cake", () -> (new BlockItem(BlockRegistry.BOOK_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> GLOW_BERRY_CAKE = ITEMS.register("glow_berry_cake", () -> (new BlockItem(BlockRegistry.GLOW_BERRY_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> PANCAKE_STACK = ITEMS.register("pancake_stack", () -> (new BlockItem(BlockRegistry.PANCAKE_STACK.get(), (new Item.Properties()).stacksTo(1))));
	public static final DeferredItem<Item> BROWNIE_TRAY = ITEMS.register("brownie_tray", () -> (new BlockItem(BlockRegistry.BROWNIE_TRAY.get(), (new Item.Properties()).stacksTo(1))));
}
