package com.morallenplay.vanillacookbook.registry;

import com.morallenplay.vanillacookbook.VanillaCookbook;
import com.morallenplay.vanillacookbook.item.CactusSliceItem;
import com.morallenplay.vanillacookbook.item.CheeseItem;
import com.morallenplay.vanillacookbook.item.ChorusJuiceItem;
import com.morallenplay.vanillacookbook.item.CureItem;
import com.morallenplay.vanillacookbook.item.IceCreamItem;
import com.morallenplay.vanillacookbook.item.JuiceItem;
import com.morallenplay.vanillacookbook.item.MilkBottleItem;
import com.morallenplay.vanillacookbook.item.SludgeItem;
import com.morallenplay.vanillacookbook.item.ContainerItem;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ItemRegistry {
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, VanillaCookbook.MOD_ID);
	
	
	public static final RegistryObject<Item> COOKED_BAMBOO = ITEMS.register("cooked_bamboo", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.3F).build())));
	public static final RegistryObject<Item> COOKED_BEETROOT = ITEMS.register("cooked_beetroot", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.4F).build())));
	public static final RegistryObject<Item> COOKED_EGG = ITEMS.register("cooked_egg", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.45F).build())));
	public static final RegistryObject<Item> GRILLED_MELON = ITEMS.register("grilled_melon", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.45F).build())));
	public static final RegistryObject<Item> BAKED_APPLE = ITEMS.register("baked_apple", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.4F).build())));
	public static final RegistryObject<Item> COOKED_TURTLE_EGG = ITEMS.register("cooked_turtle_egg", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.8F).build())));
	public static final RegistryObject<Item> CACTUS_SLICE = ITEMS.register("cactus_slice", () -> new CactusSliceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.6F).build()), 2.0F, 0.5F));
	public static final RegistryObject<Item> COOKED_CACTUS_SLICE = ITEMS.register("cooked_cactus_slice", () -> new CactusSliceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.75F).build()), 1.0F, 0.25F));
	public static final RegistryObject<Item> CHEESE = ITEMS.register("cheese", () -> new CheeseItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.3F).build())));
	public static final RegistryObject<Item> GARDEN_SOUP = ITEMS.register("garden_soup", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> PUMPKIN_SOUP = ITEMS.register("pumpkin_soup", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.75F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> FISH_STEW = ITEMS.register("fish_stew", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.2F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> VEGETABLE_STEW = ITEMS.register("vegetable_stew", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.8F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> MEATY_STEW = ITEMS.register("meaty_stew", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(7).saturationMod(1.0F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> CHICKEN_SOUP = ITEMS.register("chicken_soup", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.8F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> INK_SOUP = ITEMS.register("ink_soup", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.1F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> GLOW_INK_SOUP = ITEMS.register("glow_ink_soup", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.15F).effect(() -> new MobEffectInstance(MobEffects.GLOWING, 100, 0), 0.1F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> FUNGUS_STEW = ITEMS.register("fungus_stew", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> SMOLDERING_STEW = ITEMS.register("smoldering_stew", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.6F).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 200, 0), 1F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> PLAIN_SALAD = ITEMS.register("plain_salad", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.3F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> KELP_SALAD = ITEMS.register("kelp_salad", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(5).saturationMod(0.6F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> FRUIT_SALAD = ITEMS.register("fruit_salad", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> GOLDEN_FRUIT_SALAD = ITEMS.register("golden_fruit_salad", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.75F).effect(() -> new MobEffectInstance(MobEffects.HEAL, 1, 0), 1F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> ROOT_SALAD = ITEMS.register("root_salad", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.1F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> MASHED_POTATOES = ITEMS.register("mashed_potatoes", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.65F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> APPLE_SAUCE = ITEMS.register("apple_sauce", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(5).saturationMod(0.6F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> MUSHROOM_SCRAMBLED_EGGS = ITEMS.register("mushroom_scrambled_eggs", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.65F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> PUDDING = ITEMS.register("pudding", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.6F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> CHOCOLATE_PUDDING = ITEMS.register("chocolate_pudding", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.75F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> JELLY = ITEMS.register("jelly", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.45F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> MAGMA_JELLY = ITEMS.register("magma_jelly", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.45F).build()).craftRemainder(Items.BOWL).stacksTo(16)));
	public static final RegistryObject<Item> APPLE_PIE = ITEMS.register("apple_pie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.3F).build())));
	public static final RegistryObject<Item> BEETROOT_PIE = ITEMS.register("beetroot_pie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.35F).build())));
	public static final RegistryObject<Item> BERRY_PIE = ITEMS.register("berry_pie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(7).saturationMod(0.3F).build())));
	public static final RegistryObject<Item> WART_PIE = ITEMS.register("wart_pie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.25F).build())));
	public static final RegistryObject<Item> POISONOUS_PIE = ITEMS.register("poisonous_pie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(10).saturationMod(0.72F).effect(() -> new MobEffectInstance(MobEffects.POISON, 300, 2), 1F).effect(() -> new MobEffectInstance(MobEffects.CONFUSION, 300, 0), 1F).build())));
	public static final RegistryObject<Item> BERRY_COOKIE = ITEMS.register("berry_cookie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> HONEY_COOKIE = ITEMS.register("honey_cookie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> POTATO_COOKIE = ITEMS.register("potato_cookie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> PUMPKIN_COOKIE = ITEMS.register("pumpkin_cookie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> SUNFLOWER_SEED_COOKIE = ITEMS.register("sunflower_seed_cookie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> PANCAKE = ITEMS.register("pancake", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(5).saturationMod(0.66F).build())));
	public static final RegistryObject<Item> BERRY_PANCAKE = ITEMS.register("berry_pancake", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.65F).build())));
	public static final RegistryObject<Item> HONEY_PANCAKE = ITEMS.register("honey_pancake", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(9).saturationMod(0.7F).build())));
	public static final RegistryObject<Item> BACON_PANCAKE = ITEMS.register("bacon_pancake", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.8F).build())));
	public static final RegistryObject<Item> CREEPE = ITEMS.register("creepe", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build())));
	public static final RegistryObject<Item> BROWNIE = ITEMS.register("brownie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.55F).build())));
	public static final RegistryObject<Item> BERRY_BROWNIE = ITEMS.register("berry_brownie", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(7).saturationMod(0.5F).build())));
	public static final RegistryObject<Item> ICE_CREAM = ITEMS.register("ice_cream", () -> new IceCreamItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.6F).build())));
	public static final RegistryObject<Item> CHOCOLATE_ICE_CREAM = ITEMS.register("chocolate_ice_cream", () -> new IceCreamItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.6F).build())));
	public static final RegistryObject<Item> BERRY_ICE_CREAM = ITEMS.register("berry_ice_cream", () -> new IceCreamItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.8F).build())));
	public static final RegistryObject<Item> NEAPOLITAN_ICE_CREAM = ITEMS.register("neapolitan_ice_cream", () -> new IceCreamItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.8F).build())));
	public static final RegistryObject<Item> PUMPSICLE = ITEMS.register("pumpsicle", () -> new IceCreamItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.45F).build()).craftRemainder(Items.STICK).stacksTo(16)));
	public static final RegistryObject<Item> SNOW_HORN = ITEMS.register("snow_horn", () -> new IceCreamItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(7).saturationMod(0.6F).build())));
	public static final RegistryObject<Item> GLAZED_GLOW_BERRIES = ITEMS.register("glazed_glow_berries", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.4F).effect(() -> new MobEffectInstance(MobEffects.NIGHT_VISION, 400, 0), 1F).effect(() -> new MobEffectInstance(MobEffects.GLOWING, 400, 0), 1F).build()).craftRemainder(Items.STICK).stacksTo(16)));
	public static final RegistryObject<Item> POTATO_CHIPS = ITEMS.register("potato_chips", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.3F).fast().alwaysEat().build()), MobEffects.HUNGER, 0.5F));
	public static final RegistryObject<Item> HOT_POTATO_CHIPS = ITEMS.register("hot_potato_chips", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.3F).fast().alwaysEat().build()), MobEffects.HUNGER, 0.5F));
	public static final RegistryObject<Item> BEET_CHIPS = ITEMS.register("beet_chips", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.45F).fast().alwaysEat().build()), MobEffects.HUNGER, 0.5F));
	public static final RegistryObject<Item> APPLE_CHIPS = ITEMS.register("apple_chips", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.3F).fast().alwaysEat().build()), MobEffects.HUNGER, 0.5F));
	public static final RegistryObject<Item> HONEY_CANDY = ITEMS.register("honey_candy", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.175F).fast().alwaysEat().build()), MobEffects.HUNGER, 0.3F));
	public static final RegistryObject<Item> BERRY_CANDY = ITEMS.register("berry_candy", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.1F).fast().alwaysEat().build()), MobEffects.HUNGER, 0.3F));
	public static final RegistryObject<Item> WARPED_GUMMY = ITEMS.register("warped_gummy", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).fast().alwaysEat().build()), MobEffects.WITHER, 1.0F));
	public static final RegistryObject<Item> CHOCOLATE = ITEMS.register("chocolate", () -> new CureItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.2F).fast().alwaysEat().build()), MobEffects.HUNGER, 0.3F));
	public static final RegistryObject<Item> SWORD_LOLLIPOP = ITEMS.register("sword_lollipop", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.15F).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 600, 0), 1.0F).build()).craftRemainder(Items.STICK).stacksTo(16)));
	public static final RegistryObject<Item> TRAIL_MIX = ITEMS.register("trail_mix", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.2F).build())));
	public static final RegistryObject<Item> HOT_CHICKEN_DRUMSTICK = ITEMS.register("hot_chicken_drumstick", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.5F).build())));
	public static final RegistryObject<Item> FISH_AND_CHIPS = ITEMS.register("fish_and_chips", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(7).saturationMod(0.7F).build())));
	public static final RegistryObject<Item> KEBAB = ITEMS.register("kebab", () -> new ContainerItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(9).saturationMod(0.8F).build()).craftRemainder(Items.STICK).stacksTo(16)));
	public static final RegistryObject<Item> MEATLOAF = ITEMS.register("meatloaf", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.95F).build())));
	public static final RegistryObject<Item> MEATBALL = ITEMS.register("meatball", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.6F).fast().build())));
	public static final RegistryObject<Item> SPICY_MEATBALL = ITEMS.register("spicy_meatball", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(5).saturationMod(0.6F).fast().build())));
	public static final RegistryObject<Item> FRENCH_TOAST = ITEMS.register("french_toast", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.6F).build())));
	public static final RegistryObject<Item> POTATO_PANCAKE = ITEMS.register("potato_pancake", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.5F).build())));
	public static final RegistryObject<Item> STUFFED_SEA_PICKLE = ITEMS.register("stuffed_sea_pickle", () -> new CheeseItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(5).saturationMod(0.6F).build())));
	public static final RegistryObject<Item> MINERS_SALAD = ITEMS.register("miners_salad", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.15F).build())));
	public static final RegistryObject<Item> NETHERITE_APPLE = ITEMS.register("netherite_apple", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(1.2F).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 6000, 2), 1.0F).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 6000, 0), 1.0F).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 200, 1), 1.0F).effect(() -> new MobEffectInstance(MobEffects.ABSORPTION, 2400, 1), 1.0F).alwaysEat().build()).fireResistant().rarity(Rarity.RARE)));
	public static final RegistryObject<Item> CHOCOLATE_EGG = ITEMS.register("chocolate_egg", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.4F).build())));
	public static final RegistryObject<Item> APPLE_JUICE = ITEMS.register("apple_juice", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(3.6F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> BERRY_JUICE = ITEMS.register("berry_juice", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(2.0F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> CACTUS_JUICE = ITEMS.register("cactus_juice", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(2.4F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> MELON_JUICE = ITEMS.register("melon_juice", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(2.4F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> SEA_PICKLE_JUICE = ITEMS.register("sea_pickle_juice", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(1.8F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> CHORUS_JUICE = ITEMS.register("chorus_juice", () -> new ChorusJuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(3.6F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> LEAF_TEA = ITEMS.register("leaf_tea", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(4.8F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> FLOWER_TEA = ITEMS.register("flower_tea", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(8.0F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> MILK_BOTTLE = ITEMS.register("milk_bottle", () -> new MilkBottleItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(1.2F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> CHOCOLATE_MILK = ITEMS.register("chocolate_milk", () -> new MilkBottleItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(2.4F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> BERRY_MILK = ITEMS.register("berry_milk", () -> new MilkBottleItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(2.4F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).stacksTo(16)));
	public static final RegistryObject<Item> APPLE_SODA = ITEMS.register("apple_soda", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(7.2F).effect(() -> new MobEffectInstance(MobEffects.ABSORPTION, 400, 2), 1F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16)));
	public static final RegistryObject<Item> BERRY_SODA = ITEMS.register("berry_soda", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(4.8F).effect(() -> new MobEffectInstance(MobEffects.DIG_SPEED, 400, 1), 1F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16)));
	public static final RegistryObject<Item> CACTUS_SODA = ITEMS.register("cactus_soda", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(6.0F).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 400, 1), 1F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16)));
	public static final RegistryObject<Item> MELON_SODA = ITEMS.register("melon_soda", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(5.4F).effect(() -> new MobEffectInstance(MobEffects.HEAL, 1, 1), 1F).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 400, 0), 1F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16)));
	public static final RegistryObject<Item> SEA_PICKLE_SODA = ITEMS.register("sea_pickle_soda", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(4.0F).effect(() -> new MobEffectInstance(MobEffects.DOLPHINS_GRACE, 400, 0), 1F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16)));
	public static final RegistryObject<Item> CHORUS_SODA = ITEMS.register("chorus_soda", () -> new JuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationMod(7.2F).effect(() -> new MobEffectInstance(MobEffects.LEVITATION, 400, 1), 1F).alwaysEat().build()).craftRemainder(Items.GLASS_BOTTLE).rarity(Rarity.UNCOMMON).stacksTo(16)));
	
	public static final RegistryObject<Item> THE_SLUDGE = ITEMS.register("the_sludge", () -> new SludgeItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(0).saturationMod(0F).alwaysEat().build())));
	
	public static final RegistryObject<Item> PIZZA = ITEMS.register("pizza", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.8F).build())));
	public static final RegistryObject<Item> BERRY_CAKE_SLICE = ITEMS.register("berry_cake_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> CARROT_CAKE_SLICE = ITEMS.register("carrot_cake_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> CHEESECAKE_SLICE = ITEMS.register("cheesecake_slice", () -> new CheeseItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> CHOCOLATE_CAKE_SLICE = ITEMS.register("chocolate_cake_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> MOHNKUCHEN_SLICE = ITEMS.register("mohnkuchen_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> ICE_CREAM_CAKE_SLICE = ITEMS.register("ice_cream_cake_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> ROSE_CAKE_SLICE = ITEMS.register("rose_cake_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> CHORUS_CAKE_SLICE = ITEMS.register("chorus_cake_slice", () -> new ChorusJuiceItem(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> BOOK_CAKE_SLICE = ITEMS.register("book_cake_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	public static final RegistryObject<Item> GLOW_BERRY_CAKE_SLICE = ITEMS.register("glow_berry_cake_slice", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).build())));
	
	public static final RegistryObject<Item> BERRY_CAKE = ITEMS.register("berry_cake", () -> (new BlockItem(BlockRegistry.BERRY_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> CARROT_CAKE = ITEMS.register("carrot_cake", () -> (new BlockItem(BlockRegistry.CARROT_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> CHEESECAKE = ITEMS.register("cheesecake", () -> (new BlockItem(BlockRegistry.CHEESECAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> CHOCOLATE_CAKE = ITEMS.register("chocolate_cake", () -> (new BlockItem(BlockRegistry.CHOCOLATE_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> MOHNKUCHEN = ITEMS.register("mohnkuchen", () -> (new BlockItem(BlockRegistry.MOHNKUCHEN.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> ICE_CREAM_CAKE = ITEMS.register("ice_cream_cake", () -> (new BlockItem(BlockRegistry.ICE_CREAM_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> ROSE_CAKE = ITEMS.register("rose_cake", () -> (new BlockItem(BlockRegistry.ROSE_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> CHORUS_CAKE = ITEMS.register("chorus_cake", () -> (new BlockItem(BlockRegistry.CHORUS_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> BOOK_CAKE = ITEMS.register("book_cake", () -> (new BlockItem(BlockRegistry.BOOK_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> GLOW_BERRY_CAKE = ITEMS.register("glow_berry_cake", () -> (new BlockItem(BlockRegistry.GLOW_BERRY_CAKE.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> PANCAKE_STACK = ITEMS.register("pancake_stack", () -> (new BlockItem(BlockRegistry.PANCAKE_STACK.get(), (new Item.Properties()).stacksTo(1))));
	public static final RegistryObject<Item> BROWNIE_TRAY = ITEMS.register("brownie_tray", () -> (new BlockItem(BlockRegistry.BROWNIE_TRAY.get(), (new Item.Properties()).stacksTo(1))));
}
