
modLoader="javafml" #mandatory

loaderVersion="[46,)" #mandatory

license="https://github.com/Moralle/VanillaCookbook/blob/main/LICENCE"

issueTrackerURL="https://github.com/Moralle/VanillaCookbook/issues" #optional

[[mods]] #mandatory

modId="vanillacookbook" #mandatory

version="2.2.2" #mandatory

displayName="Vanilla Cookbook" #mandatory

# updateJSONURL="" #optional

displayURL="https://github.com/Moralle/VanillaCookbook" #optional

logoFile="vanilla_cookbook.png" #optional

logoBlur=false

itemIcon="vanillacookbook:book_cake"

configBackground="minecraft:textures/block/stripped_spruce_log.png"

credits="Moralle for making the actual mod. My friends Lars, Duo, and Multi for their support and input." #optional

authors="Moralle" #optional

description='''
A mod expanding food while staying close to vanilla Minecraft.
'''

[[dependencies.vanillacookbook]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillacookbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
